baseURL = 'https://autoscaler.sh/'
locale = 'en-US'
timeZone = 'America/Los_Angeles'
title = 'autoscaler.sh'
theme = 'quiet'
enableRobotsTXT = true
disableKinds = ['taxonomy', 'term']

[params]
  author = 'Swapnil Patel'
  description = 'Notes by Swapnil Patel.'
  headline = 'as i understand it'
  intro = '[Swapnil Patel](https://github.com/swap357)'

[outputs]
  home = ['HTML', 'RSS']
  section = ['HTML']

[markup.highlight]
  noClasses = false

[markup.goldmark.renderer]
  unsafe = false
